"""Constants for Advanced Presence Detection."""

from homeassistant.const import Platform

DOMAIN = "advanced_presence_detection"
PLATFORMS: list[Platform] = [Platform.BINARY_SENSOR]

CONF_DOOR_ENTITIES = "door_entities"
CONF_CONTROL_ENTITIES = CONF_DOOR_ENTITIES
CONF_CONTROL_ACTIVE_STATES = "control_active_states"
CONF_MOTION_ENTITIES = "motion_entities"
CONF_MOTION_COOLDOWNS = "motion_cooldowns"
CONF_DEFAULT_COOLDOWN = "default_cooldown"
CONF_FRESH_WINDOW = "fresh_window"
CONF_CONTROL_GRACE_TIME = CONF_FRESH_WINDOW
CONF_NO_MOTION_TIMEOUT = "no_motion_timeout"
CONF_OPEN_NO_MOTION_TIMEOUT = "open_no_motion_timeout"
CONF_CONTROL_CLOSED_MODE = "control_closed_mode"
CONF_UNAVAILABLE_BEHAVIOR = "unavailable_behavior"
CONF_SHOW_DEBUG_ATTRIBUTES = "show_debug_attributes"

CONTROL_ENTITY_DOMAINS = ("binary_sensor", "switch", "input_boolean", "fan")

DEFAULT_NAME = "Advanced Presence Detection"
DEFAULT_COOLDOWN = 180
DEFAULT_FRESH_WINDOW = 15
DEFAULT_NO_MOTION_TIMEOUT = 3600
DEFAULT_OPEN_NO_MOTION_TIMEOUT = 0
DEFAULT_CONTROL_CLOSED_MODE = "all"
DEFAULT_UNAVAILABLE_BEHAVIOR = "mark_unavailable"
DEFAULT_SHOW_DEBUG_ATTRIBUTES = False

MIN_COOLDOWN = 1
MAX_COOLDOWN = 3600
MIN_CONTROL_GRACE_TIME = 0
MAX_CONTROL_GRACE_TIME = 300
MIN_TIMEOUT_MINUTES = 0
MAX_TIMEOUT_MINUTES = 1440
MIN_TIMEOUT_SECONDS = MIN_TIMEOUT_MINUTES * 60
MAX_TIMEOUT_SECONDS = MAX_TIMEOUT_MINUTES * 60

CONTROL_CLOSED_MODE_ALL = "all"
CONTROL_CLOSED_MODE_ANY = "any"

UNAVAILABLE_BEHAVIOR_MARK_UNAVAILABLE = "mark_unavailable"
UNAVAILABLE_BEHAVIOR_TREAT_INACTIVE = "treat_inactive"
